buildscript {
    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.4'
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.google.com' }
    }

    rootProject.ext {
        MinSdk = 16
        TargetSdk = 31
        CompileSdk = 31
        // specify build tools v31 otherwise gradle (7.0.4) selects v30.0.2 and tries to install it (which crashes on nix)
        BuildTools = "31.0.0"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
