// TODO: Remove `/*` and `*/` below to enable OneSignal
/*
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.13.4'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
*/
apply plugin: 'com.android.application'

// load local release signing values
// Note: file is ignored by Git.
def releaseSigningPropertiesFile = rootProject.file('signing.properties')
def releaseSigningProperties = new Properties()

if (releaseSigningPropertiesFile.exists()) {
    releaseSigningPropertiesFile.withInputStream { signingPropertiesInputStream ->
        releaseSigningProperties.load(signingPropertiesInputStream)
    }
}

android {
    compileSdk rootProject.ext.CompileSdk

    namespace 'io.github.PapirusDevelopmentTeam.papirus_icons'

    defaultConfig {
        applicationId "io.github.PapirusDevelopmentTeam.papirus_icons"
        minSdkVersion rootProject.ext.MinSdk
        targetSdkVersion rootProject.ext.TargetSdk
        versionCode 14
        versionName "20260801.3"
    }

    bundle {
        language {
            enableSplit false
        }
    }
    
    signingConfigs {
        release {
            if (releaseSigningPropertiesFile.exists()) {
                storeFile rootProject.file(releaseSigningProperties['storeFile'])
                storePassword releaseSigningProperties['storePassword']
                keyAlias releaseSigningProperties['keyAlias']
                keyPassword releaseSigningProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            debuggable false
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}

androidComponents {
    onVariants(selector().all()) { variant ->
        // Use app version instead of version code. Example: papirus-android-v20260801.2-debug.apk.
        variant.outputs.forEach { output ->
            def applicationVariantVersionName = output.versionName.get()
            output.outputFileName.set("${rootProject.name}-v${applicationVariantVersionName}-${variant.name}.apk")
        }
    }
}

dependencies {
    /*
     * CandyBar Material Dashboard Library
     *
     * TODO: How to update the dashboard?!
     * Check this update guide for every version
     *      - https://github.com/zixpo/candybar-sample/wiki/Updating-the-dashboard
     * If you've missed some versions you've to also follow update guide for those versions
     */

    implementation 'com.github.zixpo.candybar:library:3.23.0'

    // TODO: Remove `//` below to enable OneSignal
    //implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'
}
